import { useState, type FormEvent } from 'react';
import { ArrowLeft, Lock, Mail, UserRound } from 'lucide-react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import Logo from '../components/Logo';
import { ErrorNotice } from '../components/ui';
import { useAuth } from '../contexts/AuthContext';
import { isSupabaseConfigured, messageFromError, supabase, supabaseConfigurationError } from '../lib/supabase';
type Mode='login'|'signup'|'forgot'|'reset';
export default function Auth({mode}:{mode:Mode}){
 const{user,loading}=useAuth();const nav=useNavigate();const location=useLocation();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[name,setName]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 if(!loading&&user&&mode!=='reset')return <Navigate to={(location.state as{from?:{pathname:string}}|null)?.from?.pathname??'/app'} replace/>;
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{if(!isSupabaseConfigured)throw new Error(supabaseConfigurationError??'Supabase is not configured.');if(mode==='login'){const{error:e2}=await supabase.auth.signInWithPassword({email,password});if(e2)throw e2;nav('/app')}else if(mode==='signup'){const{error:e2}=await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:`${window.location.origin}/auth/callback`}});if(e2)throw e2;setNotice('Check your email to confirm your account, then sign in.')}else if(mode==='forgot'){const{error:e2}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});if(e2)throw e2;setNotice('Password reset instructions sent.')}else{const{error:e2}=await supabase.auth.updateUser({password});if(e2)throw e2;setNotice('Password updated. You can continue to the app.')}}catch(err){setError(messageFromError(err))}finally{setBusy(false)}};
 const titles={login:'Welcome back',signup:'Create your account',forgot:'Reset your password',reset:'Choose a new password'};
 return <div className="min-h-screen grid lg:grid-cols-2 bg-paper"><section className="hidden lg:flex bg-midnight-900 text-white p-14 flex-col justify-between relative overflow-hidden"><div className="absolute inset-0 bg-gateway-glow"/><div className="relative w-fit rounded-xl bg-white px-3"><Logo className="w-36 h-14"/></div><div className="relative max-w-lg"><p className="eyebrow text-gold-light">Faggala Fantasy</p><h1 className="font-display font-extrabold text-5xl leading-tight">Enter the gateway. Build your legend.</h1><p className="text-mist/70 mt-5">Build a legal squad, follow every live point and compete with your community.</p></div><p className="relative text-xs text-mist/40">Securely powered by Supabase Auth</p></section><main className="p-6 grid place-items-center"><div className="w-full max-w-md"><Link to="/" className="inline-flex items-center gap-2 text-sm text-midnight-600 mb-8"><ArrowLeft size={16}/>Back home</Link><p className="eyebrow">Your gateway</p><h2 className="font-display text-3xl font-bold text-midnight-900 mb-6">{titles[mode]}</h2>{error&&<div className="mb-4"><ErrorNotice message={error}/></div>}{notice&&<div className="notice">{notice}</div>}<form onSubmit={submit} className="space-y-4">{mode==='signup'&&<label className="field"><span>Full name</span><div><UserRound/><input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></div></label>}{mode!=='reset'&&<label className="field"><span>Email</span><div><Mail/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></div></label>}{mode!=='forgot'&&<label className="field"><span>Password</span><div><Lock/><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'}/></div></label>}<button disabled={busy} className="btn-primary w-full">{busy?'Please wait…':titles[mode]}</button></form><div className="mt-5 text-sm text-midnight-600 flex justify-between">{mode==='login'?<><Link to="/signup">Create account</Link><Link to="/forgot-password">Forgot password?</Link></>:<Link to="/login">Return to login</Link>}</div></div></main></div>;
}
