import { useEffect, useMemo, useState } from 'react';
import { LayoutList, LockKeyhole, RotateCcw, Save, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import PlayerChip from '../components/PlayerChip';
import { EmptyState, ErrorNotice, LoadingScreen, PageHeader } from '../components/ui';
import { formationValid } from '../lib/fantasyRules';
import { cairoDate, deadlineOpen, money } from '../lib/format';
import { supabase } from '../lib/supabase';
import type { FantasyRules, FantasyTeam, Gameweek, PlayerPosition, SquadPlayer } from '../types/database';

export default function MyTeam(){
 const[team,setTeam]=useState<FantasyTeam|null>(null);const[gw,setGw]=useState<Gameweek|null>(null);const[rules,setRules]=useState<FantasyRules|null>(null);const[squad,setSquad]=useState<SquadPlayer[]>([]);const[original,setOriginal]=useState<SquadPlayer[]>([]);const[selected,setSelected]=useState<string|null>(null);const[view,setView]=useState<'pitch'|'list'>('pitch');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const load=async()=>{const t=await supabase.from('fantasy_teams').select('*,fantasy_leagues(name,season_id)').order('created_at').limit(1).maybeSingle();if(t.error){setError(t.error.message);setLoading(false);return}const ft=t.data as FantasyTeam|null;setTeam(ft);if(ft){const[s,g,r]=await Promise.all([supabase.from('fantasy_team_players').select('*,players(*,teams(*))').eq('fantasy_team_id',ft.id),supabase.from('gameweeks').select('*').eq('season_id',ft.fantasy_leagues!.season_id).in('status',['upcoming','locked','active']).order('number').limit(1).maybeSingle(),supabase.rpc('get_fantasy_team_rules',{p_team_id:ft.id})]);const rows=(s.data??[])as SquadPlayer[];setSquad(rows);setOriginal(rows);setGw(g.data as Gameweek|null);setRules(r.data as FantasyRules|null);setError(s.error?.message??g.error?.message??r.error?.message??'')}setLoading(false)};
 useEffect(()=>{void load()},[]);
 const open=deadlineOpen(gw?.transfer_deadline)&&gw?.status==='upcoming';const dirty=JSON.stringify(squad.map(x=>[x.id,x.is_bench,x.bench_order,x.is_captain,x.is_vice_captain]))!==JSON.stringify(original.map(x=>[x.id,x.is_bench,x.bench_order,x.is_captain,x.is_vice_captain]));
 const groups=useMemo(()=>Object.fromEntries((['GK','DEF','MID','FWD']as PlayerPosition[]).map(pos=>[pos,squad.filter(x=>!x.is_bench&&x.players.position===pos)]))as Record<PlayerPosition,SquadPlayer[]>,[squad]);
 if(loading)return <LoadingScreen/>;if(!team)return <><PageHeader title="My Team"/><EmptyState title="No fantasy team yet" message="Join a league and build your first squad." action={<Link to="/app/leagues" className="btn-primary">Browse leagues</Link>}/></>;
 const choose=(id:string)=>{if(!open)return;setNotice('');if(!selected){setSelected(id);return}if(selected===id){setSelected(null);return}const a=squad.find(x=>x.id===selected),b=squad.find(x=>x.id===id);if(a&&b&&a.is_bench!==b.is_bench){const candidate=squad.map(x=>x.id===a.id?{...x,is_bench:b.is_bench,bench_order:b.bench_order,is_captain:false,is_vice_captain:false}:x.id===b.id?{...x,is_bench:a.is_bench,bench_order:a.bench_order,is_captain:false,is_vice_captain:false}:x);const starters=candidate.filter(x=>!x.is_bench).map(x=>({position:x.players.position}));if(!formationValid(starters,rules??undefined)){setError('That swap would create a formation that is not allowed for this league.')}else{setSquad(candidate);setError('')}}else setError('Select one starter and one bench player to make a substitution.');setSelected(null)};
 const role=(id:string,type:'c'|'v')=>{setNotice('');setSquad(items=>items.map(x=>({...x,is_captain:type==='c'?x.id===id:x.is_captain&&x.id!==id,is_vice_captain:type==='v'?x.id===id:x.is_vice_captain&&x.id!==id})).map(x=>x.id===id?{...x,is_captain:type==='c',is_vice_captain:type==='v'}:x))};
 const save=async()=>{const captain=squad.find(x=>x.is_captain),vice=squad.find(x=>x.is_vice_captain);if(!captain||!vice){setError('Choose one captain and a different vice-captain before saving.');return}setBusy(true);setError('');const payload=squad.map(x=>({player_id:x.player_id,is_bench:x.is_bench,bench_order:x.bench_order,is_captain:x.is_captain,is_vice_captain:x.is_vice_captain}));const{error:e}=await supabase.rpc('save_lineup',{p_team_id:team.id,p_lineup:payload});if(e)setError(e.message);else{setOriginal(squad);setNotice('Lineup saved and validated.')}setBusy(false)};
 const reset=()=>{setSquad(original);setSelected(null);setError('');setNotice('Changes reset.')};
 return <><PageHeader eyebrow={`${team.fantasy_leagues?.name} · Bank ${money(team.bank)}`} title={team.name}><div className="flex gap-2"><button className={view==='pitch'?'filter-active':'filter'} onClick={()=>setView('pitch')}>Pitch</button><button className={view==='list'?'filter-active':'filter'} onClick={()=>setView('list')}><LayoutList size={14}/>List</button></div></PageHeader>
 {gw&&<div className={`mb-5 rounded-xl border p-4 flex flex-wrap items-center justify-between gap-3 ${open?'bg-white border-mist':'bg-midnight-900 text-white border-midnight-900'}`}><div><p className="font-semibold">{open?'Lineup editing is open':'Team locked until the next round.'}</p><p className="text-sm opacity-65">{gw.name??`Gameweek ${gw.number}`} deadline · {cairoDate(gw.transfer_deadline)}</p></div>{open?<span className="status-available"><ShieldCheck size={13}/> Open</span>:<span className="status-pill"><LockKeyhole size={13}/> Locked</span>}</div>}
 {error&&<div className="mb-4"><ErrorNotice message={error}/></div>}{notice&&<div className="notice" role="status">{notice}</div>}
 <div className="grid xl:grid-cols-[1fr_310px] gap-5">{view==='pitch'?<section className="pitch" aria-label="Starting eleven">{(['GK','DEF','MID','FWD']as PlayerPosition[]).map(pos=><div key={pos} className="pitch-row"><span className="pitch-label">{pos}</span>{groups[pos].map(x=><PlayerChip key={x.id} entry={x} selected={selected===x.id} onClick={()=>choose(x.id)}/>)}</div>)}</section>:<section className="panel"><div className="section-title"><h2>Starting XI</h2><span className="text-xs text-midnight-600">{squad.filter(x=>!x.is_bench).length} players</span></div><div className="space-y-2">{squad.filter(x=>!x.is_bench).map(x=><button key={x.id} onClick={()=>choose(x.id)} className={`player-row w-full text-left ${selected===x.id?'border-gold bg-gold/5':''}`}><span className="position-tag">{x.players.position}</span><span className="flex-1"><strong>{x.players.name}</strong><small className="block text-midnight-600">{x.players.teams?.name??'No team'}</small></span>{x.is_captain&&<span className="role-badge static">C</span>}{x.is_vice_captain&&<span className="role-badge static">V</span>}</button>)}</div></section>}
 <aside className="space-y-5"><div className="panel"><div className="section-title"><h2>Substitutes</h2><span className="text-xs text-midnight-600">Select to swap</span></div><div className="grid grid-cols-2 gap-2">{squad.filter(x=>x.is_bench).sort((a,b)=>(a.bench_order??9)-(b.bench_order??9)).map(x=><div key={x.id}><span className="text-[10px] text-midnight-600">{x.bench_order===1?'GK':`Bench ${(x.bench_order??1)-1}`}</span><PlayerChip entry={x} selected={selected===x.id} onClick={()=>choose(x.id)}/></div>)}</div></div>{open&&<div className="panel"><h2 className="font-display font-bold">Captaincy</h2><p className="text-xs text-midnight-600 my-2">Captain scores double. Vice-captain takes over if needed.</p><div className="space-y-2 max-h-64 overflow-y-auto">{squad.filter(x=>!x.is_bench).map(x=><div className="flex justify-between text-sm" key={x.id}><span className="truncate">{x.players.name}</span><span className="flex gap-1"><button aria-label={`Make ${x.players.name} captain`} className={x.is_captain?'mini-active':'mini'} onClick={()=>role(x.id,'c')}>C</button><button aria-label={`Make ${x.players.name} vice-captain`} className={x.is_vice_captain?'mini-active':'mini'} onClick={()=>role(x.id,'v')}>V</button></span></div>)}</div></div>}</aside></div>
 {open&&dirty&&<div className="sticky bottom-20 lg:bottom-4 z-20 mt-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-midnight-900 p-4 text-white shadow-xl"><div><strong>Unsaved lineup changes</strong><p className="text-xs text-white/50">Save before the deadline for your changes to count.</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={reset}><RotateCcw size={15}/>Reset</button><button onClick={()=>void save()} disabled={busy} className="btn-primary"><Save size={16}/>{busy?'Saving…':'Save team'}</button></div></div>}
 </>;
}
